import { useState } from 'react'
import { Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { GraduationCap, UploadCloud, ShieldCheck, CheckCircle2, ArrowLeft, Play, Files, BookOpen } from 'lucide-react'

const roles = [
  { label: 'أنا طالب', icon: GraduationCap, title: 'فصلُك المفضّل، معاك في كل مكان.', description: 'شرح واضح، ملفات منظّمة، وخطوة جديدة كل يوم. كل اللي محتاجه للتعلّم هتلاقيه في مكتبتك.', steps: ['شاهد فيديوهات مدرسك داخل الدرس', 'حمّل المذكرات وراجع الشرح في أي وقت', 'تابع تقدّمك وسلّم واجباتك واختبر نفسك'], cta: 'ابدأ التعلّم', to: '/register', card: 'مساحة التعلّم', items: ['شاهد الشرح', 'راجع ملفات الدرس', 'كمّل رحلتك'] },
  { label: 'أنا مدرس', icon: UploadCloud, title: 'ركّز في الشرح. ومدارك تجمع الباقي.', description: 'مساحة لمحتواك وأفكارك، توصل بيها لكل طالب وتعرف مين بدأ ومين أكمل ومين محتاج مساعدتك.', steps: ['قسّم الكورس لفصول ودروس بالترتيب', 'ارفع الفيديوهات والملفات في نفس الدرس', 'تابع تقدّم الطلاب بجانب الواجبات والدرجات'], cta: 'ادخل لاستوديو المدرس', to: '/login', card: 'استوديو المحتوى', items: ['نظّم فصول الكورس', 'ارفع فيديو وملفات', 'تابع رحلة طلابك'] },
  { label: 'أنا إدارة', icon: ShieldCheck, title: 'كل التفاصيل، في صورة أوضح.', description: 'اجمع المحتوى التعليمي ومتابعة المدرسين والطلاب مع الحضور والمدفوعات والتقارير في منصة واحدة.', steps: ['راجع محتوى الكورسات والدروس المرفوعة', 'تابع إنجاز الطلاب وآخر نشاط لهم', 'اربط المتابعة بالحضور والدرجات والمدفوعات'], cta: 'تواصل لتجهيز منصتك', to: '/contact', card: 'مركز المتابعة', items: ['محتوى المدرسين', 'تقدّم الطلاب', 'التقارير والمتابعة'] },
]
export default function LearningJourney() {
  const [index, setIndex] = useState(0)
  const role = roles[index]
  return <section className="bg-white px-5 py-20" id="learning-journey"><div className="mx-auto max-w-6xl">
    <div className="text-center"><p className="text-xs font-extrabold tracking-widest text-teal-600">تجربة متصلة، من البداية للنهاية</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">ثلاث مساحات. رحلة نجاح واحدة.</h2><div className="mx-auto mt-7 inline-flex max-w-full flex-wrap justify-center gap-1 rounded-2xl bg-slate-100 p-1.5" role="tablist" aria-label="مساحات المنصة">{roles.map((r, i) => <button key={r.label} role="tab" aria-selected={i === index} onClick={() => setIndex(i)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold transition sm:px-6 ${i === index ? 'bg-white text-teal-700 shadow-sm' : 'text-ink-500 hover:text-teal-700'}`}><r.icon size={17} />{r.label}</button>)}</div></div>
    <AnimatePresence mode="wait"><motion.div role="tabpanel" key={index} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .25 }} className="mt-12 grid items-center gap-10 lg:grid-cols-2">
      <div><h3 className="text-2xl font-black leading-relaxed">{role.title}</h3><p className="mt-4 leading-8 text-ink-500">{role.description}</p><div className="mt-6 space-y-4">{role.steps.map(s => <p key={s} className="flex items-center gap-3 text-sm font-semibold text-ink-700"><CheckCircle2 size={18} className="shrink-0 text-teal-500" />{s}</p>)}</div><Link to={role.to} className="mt-7 btn-primary px-6">{role.cta}<ArrowLeft size={17} /></Link></div>
      <div className="rounded-[32px] border border-teal-100 bg-[#f0f7f7] p-5 sm:p-9"><div className="overflow-hidden rounded-2xl border border-white bg-white shadow-xl shadow-teal-900/5"><div className="flex items-center justify-between border-b border-ink-100 px-5 py-4"><span className="flex items-center gap-2 text-sm font-extrabold"><BookOpen size={18} className="text-teal-600" />{role.card}</span><span className="text-[10px] text-ink-400">جولة في التجربة</span></div><div className="p-5"><div className="learning-banner rounded-2xl p-6 text-white"><role.icon size={28} className="text-lime-300" /><p className="mt-4 text-lg font-extrabold">المعرفة تبدأ بخطوة.</p><p className="mt-2 text-xs text-slate-300">مدارك معاك في كل خطوة.</p></div><div className="mt-5 space-y-2">{role.items.map((item, i) => <div key={item} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white text-teal-600">{i === 0 ? <Play size={16} /> : i === 1 ? <Files size={16} /> : <CheckCircle2 size={16} />}</span><span className="text-xs font-bold">{item}</span><span className="mr-auto text-xs text-ink-300">0{i + 1}</span></div>)}</div></div></div></div>
    </motion.div></AnimatePresence>
  </div></section>
}
