import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Users, ListChecks, Download, ShieldAlert, Search, Clock, Eye, AlertTriangle, ArrowRight } from 'lucide-react'
import api from '../../lib/api'
import { Modal, PageLoader, EmptyState } from '../../components/ui'
import { downloadCsv, formatDuration } from '../../lib/csv'
import ExamReview from './ExamReview'
import { apiErrorMessage } from '../../lib/apiError'

const STATUS = { GRADED: ['مُصحَّح', 'bg-emerald-50 text-emerald-700'], SUBMITTED: ['بانتظار التصحيح اليدوي', 'bg-amber-50 text-amber-700'], IN_PROGRESS: ['يحل الآن', 'bg-sky-50 text-sky-700'], NOT_STARTED: ['لم يبدأ', 'bg-ink-100 text-ink-500'] }
const EVENT = { TAB_HIDDEN: 'غادر صفحة الامتحان', TAB_VISIBLE: 'عاد للصفحة', FULLSCREEN_EXIT: 'خرج من ملء الشاشة', FULLSCREEN_ENTER: 'عاد لملء الشاشة', COPY_BLOCKED: 'حاول النسخ', PASTE_BLOCKED: 'حاول اللصق', RESUME: 'استكمل محاولة محفوظة', WINDOW_BLUR: 'انتقل لنافذة أخرى' }
const flagLevel = r => (r.tabSwitches >= 3 || r.fullscreenExits >= 2) ? 'high' : (r.tabSwitches > 0 || r.fullscreenExits > 0) ? 'low' : 'none'

/** Teacher results workspace: cohort overview, per-student table with integrity flags, and item analysis. */
export default function ExamResults({ exam, onClose }) {
  const [a, setA] = useState(null), [tab, setTab] = useState('overview'), [review, setReview] = useState(null), [integrity, setIntegrity] = useState(null), [error, setError] = useState('')
  const [query, setQuery] = useState(''), [filter, setFilter] = useState('all')
  const load = () => api.get(`/exams/${exam.id}/results`).then(r => setA(r.data)).catch(e => setError(apiErrorMessage(e, 'تعذّر تحميل النتائج')))
  useEffect(() => { load() }, [exam.id])
  const rows = useMemo(() => (a?.rows || []).filter(r => r.studentName.includes(query) && (filter === 'all' || (filter === 'pending' ? r.needsManualGrade : filter === 'flagged' ? flagLevel(r) !== 'none' : filter === 'failed' ? r.status !== 'IN_PROGRESS' && r.percent < exam.passPercent : true))).sort((x, y) => y.percent - x.percent), [a, query, filter, exam.passPercent])
  const exportCsv = () => downloadCsv(`${exam.title}-results.csv`, ['الطالب', 'الحالة', 'الدرجة', 'من', 'النسبة', 'الوقت المستغرق', 'مغادرة الصفحة', 'خروج من ملء الشاشة', 'وقت التسليم'],
    (a?.rows || []).map(r => [r.studentName, STATUS[r.status]?.[0] || r.status, r.score, r.maxScore, r.percent, formatDuration(r.durationSeconds), r.tabSwitches, r.fullscreenExits, r.submittedAt ? new Date(r.submittedAt).toLocaleString('ar-EG') : '']))
  return <Modal open onClose={onClose} title={`نتائج · ${exam.title}`} size="xl">
    {review ? <ExamReview row={review} onBack={() => { setReview(null); load() }} /> : integrity ? <IntegrityPanel report={integrity} onBack={() => setIntegrity(null)} /> : error ? <p role="alert" className="rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p> : !a ? <PageLoader /> : <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">{[['overview', 'نظرة عامة', BarChart3], ['students', `الطلاب (${a.rows.length})`, Users], ['items', 'تحليل الأسئلة', ListChecks]].map(([k, v, Icon]) => <button key={k} onClick={() => setTab(k)} className={`chip border ${tab === k ? 'border-brand-600 bg-brand-600 text-white' : 'border-ink-200 bg-white text-ink-600'}`}><Icon size={14} /> {v}</button>)}<span className="flex-1" /><button onClick={exportCsv} className="btn-ghost" disabled={!a.rows.length}><Download size={15} /> تصدير CSV</button></div>
      {tab === 'overview' && <div className="space-y-4">
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['المحاولات', a.attempts, ''], ['سلّموا', a.submitted, ''], ['المتوسط', a.avgPercent + '٪', ''], ['الوسيط', a.medianPercent + '٪', ''], ['الأعلى', a.highest + '٪', 'text-emerald-700'], ['الأدنى', a.lowest + '٪', 'text-rose-700'], ['نسبة النجاح', a.passRate + '٪', ''], ['بانتظار التصحيح', a.pendingManual, a.pendingManual ? 'text-amber-700' : '']].map(([l, v, c]) => <div key={l} className="rounded-2xl bg-ink-50 p-4 text-center"><p className={`text-2xl font-black ${c || 'text-ink-800'}`}>{v}</p><p className="text-xs text-ink-500">{l}</p></div>)}</div>
        {a.flagged > 0 && <p className="flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-800"><ShieldAlert size={17} /> {a.flagged} محاولة عليها مؤشرات نزاهة مرتفعة (مغادرة متكررة أو خروج من ملء الشاشة). راجعها من تبويب الطلاب.</p>}
        <div className="rounded-2xl border border-ink-200 p-4"><p className="mb-3 text-sm font-bold">توزيع الدرجات</p>{a.submitted === 0 ? <p className="text-xs text-ink-400">لا توجد تسليمات بعد</p> : <div className="space-y-2">{['0-19٪', '20-39٪', '40-59٪', '60-79٪', '80-100٪'].map((l, i) => { const n = a.distribution[i]; const w = a.submitted ? Math.round(n / a.submitted * 100) : 0; return <div key={l} className="flex items-center gap-3 text-xs"><span className="w-16 tabular-nums text-ink-500">{l}</span><div className="h-4 flex-1 overflow-hidden rounded-lg bg-ink-100"><div className={`h-full rounded-lg ${i < 2 ? 'bg-rose-400' : i === 2 ? 'bg-amber-400' : 'bg-emerald-500'}`} style={{ width: `${w}%` }} /></div><span className="w-16 tabular-nums font-bold">{n} طالب</span></div> })}</div>}</div>
      </div>}
      {tab === 'students' && <div className="space-y-3">
        <div className="flex flex-wrap gap-2"><label className="relative flex-1 sm:max-w-xs"><Search size={15} className="absolute right-3 top-3 text-ink-400" /><input className="input pr-9" placeholder="ابحث باسم الطالب" value={query} onChange={e => setQuery(e.target.value)} /></label>{[['all', 'الكل'], ['pending', 'بانتظار التصحيح'], ['flagged', 'مؤشرات نزاهة'], ['failed', 'لم يجتز']].map(([k, v]) => <button key={k} className={filter === k ? 'btn-primary' : 'btn-ghost'} onClick={() => setFilter(k)}>{v}</button>)}</div>
        {!rows.length ? <EmptyState icon={Users} title="لا توجد محاولات مطابقة" /> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><caption className="sr-only">نتائج الطلاب</caption>
          <thead><tr className="text-right text-xs text-ink-400"><th className="pb-2 font-semibold">الطالب</th><th className="pb-2 font-semibold">الحالة</th><th className="pb-2 font-semibold">الدرجة</th><th className="pb-2 font-semibold">الوقت</th><th className="pb-2 font-semibold">النزاهة</th><th className="pb-2 font-semibold">إجراءات</th></tr></thead>
          <tbody className="divide-y divide-ink-100">{rows.map(r => { const lvl = flagLevel(r); return <tr key={r.studentExamId} className="h-12"><td className="font-semibold text-ink-700">{r.studentName}</td><td><span className={`chip ${STATUS[r.status]?.[1]}`}>{STATUS[r.status]?.[0] || r.status}</span></td><td className="tabular-nums"><b className={r.status === 'IN_PROGRESS' ? 'text-ink-400' : r.percent >= exam.passPercent ? 'text-emerald-700' : 'text-rose-700'}>{r.score}/{r.maxScore}</b> <span className="text-xs text-ink-400">{r.percent}٪</span></td><td className="text-xs text-ink-500"><Clock size={12} className="inline" /> {formatDuration(r.durationSeconds)}</td><td>{lvl === 'none' ? <span className="text-xs text-emerald-700">نظيف</span> : <button onClick={() => api.get(`/exams/attempts/${r.studentExamId}/integrity`).then(x => setIntegrity(x.data))} className={`chip ${lvl === 'high' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}><AlertTriangle size={12} /> {r.tabSwitches > 0 && `${r.tabSwitches} مغادرة`}{r.tabSwitches > 0 && r.fullscreenExits > 0 && ' · '}{r.fullscreenExits > 0 && `${r.fullscreenExits} خروج`}</button>}</td><td>{r.status !== 'IN_PROGRESS' && <button onClick={() => setReview(r)} className={`btn-soft px-3 py-1.5 text-xs ${r.needsManualGrade ? 'ring-2 ring-amber-300' : ''}`}><Eye size={13} /> {r.needsManualGrade ? 'تصحيح المقالي' : 'الإجابات'}</button>}</td></tr> })}</tbody></table></div>}
      </div>}
      {tab === 'items' && (a.questionStats.length === 0 ? <EmptyState icon={ListChecks} title="لا توجد أسئلة تفاعلية" /> : <div className="space-y-2"><p className="text-xs text-ink-500">نسبة الإجابات الصحيحة لكل سؤال بين الطلاب الذين سلّموا؛ الأسئلة الحمراء صعبة أو غامضة وتستحق مراجعة الصياغة.</p>
        {[...a.questionStats].sort((x, y) => x.correctRate - y.correctRate).map((s, i) => <div key={s.questionId} className="rounded-xl border border-ink-100 p-3"><div className="flex items-start justify-between gap-3"><p className="min-w-0 flex-1 text-sm font-semibold leading-6">{a.questionStats.indexOf(s) + 1}. {s.stem}</p><span className={`shrink-0 text-sm font-black ${s.correctRate < 40 ? 'text-rose-600' : s.correctRate < 70 ? 'text-amber-600' : 'text-emerald-700'}`}>{s.type === 'ESSAY' ? `${s.avgPoints}/${s.points}` : `${s.correctRate}٪`}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-ink-100"><div className={`h-full ${s.correctRate < 40 ? 'bg-rose-400' : s.correctRate < 70 ? 'bg-amber-400' : 'bg-emerald-500'}`} style={{ width: `${s.type === 'ESSAY' ? (s.points ? s.avgPoints / s.points * 100 : 0) : s.correctRate}%` }} /></div><p className="mt-1 text-[11px] text-ink-400">{s.answered} أجابوا · {s.correct} صحيحة · متوسط {s.avgPoints} من {s.points}</p></div>)}</div>)}
    </div>}
  </Modal>
}

function IntegrityPanel({ report, onBack }) {
  return <div className="space-y-4"><button onClick={onBack} className="btn-ghost"><ArrowRight size={16} /> العودة للنتائج</button>
    <div className="rounded-2xl bg-ink-50 p-4"><h3 className="font-black">تقرير نزاهة المحاولة · {report.studentName}</h3><p className="mt-1 text-xs text-ink-500">بدأ {report.startedAt ? new Date(report.startedAt).toLocaleString('ar-EG') : '—'} · سلّم {report.submittedAt ? new Date(report.submittedAt).toLocaleString('ar-EG') : 'لم يسلّم'} · استغرق {formatDuration(report.durationSeconds)}</p>
      <div className="mt-3 flex flex-wrap gap-2"><span className="chip bg-white">{report.tabSwitches} مغادرة للصفحة</span><span className="chip bg-white">{report.fullscreenExits} خروج من ملء الشاشة</span><span className="chip bg-white">{report.events.length} حدث مسجّل</span></div></div>
    <p className="rounded-xl bg-amber-50 p-3 text-xs leading-6 text-amber-800">هذه الأحداث يرسلها متصفح الطالب وهي مؤشرات مساعدة وليست دليلاً على الغش: انقطاع الإنترنت أو إشعار من النظام قد يسببان مغادرة قصيرة.</p>
    <ol className="max-h-80 space-y-1 overflow-y-auto">{report.events.map((e, i) => <li key={i} className="flex items-center gap-3 rounded-lg border border-ink-100 p-2 text-sm"><span className="w-20 shrink-0 text-xs tabular-nums text-ink-400">{new Date(e.at).toLocaleTimeString('ar-EG')}</span><span className={['FULLSCREEN_EXIT', 'TAB_HIDDEN', 'WINDOW_BLUR', 'COPY_BLOCKED', 'PASTE_BLOCKED'].includes(e.type) ? 'font-bold text-rose-700' : 'text-ink-600'}>{EVENT[e.type] || e.type}</span></li>)}{!report.events.length && <li className="p-4 text-center text-xs text-ink-400">لا أحداث مسجّلة</li>}</ol>
  </div>
}
